DROP TABLE IF EXISTS genders; DROP TABLE IF EXISTS students; DROP TABLE IF EXISTS genders; DROP TABLE IF EXISTS teachers; DROP TABLE IF EXISTS groups; DROP TABLE IF EXISTS subjects;

CREATE TABLE students (
  students_id INTEGER PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  email VARCHAR(30) NOT NULL UNIQUE,
  phone VARCHAR(30) NOT NULL UNIQUE,
  gender_id INT,
  grades_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (gender_id) REFERENCES genders (students_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  FOREIGN KEY (grades_id) REFERENCES grades (id)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

CREATE TABLE teachers (
  teachers_id INTEGER PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  email VARCHAR(30) NOT NULL UNIQUE,
  phone VARCHAR(30) NOT NULL UNIQUE,
  gender_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (gender_id) REFERENCES genders (teachers_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

CREATE TABLE genders (
  id INTEGER PRIMARY KEY,
  name VARCHAR(30),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE grades (
  id INTEGER PRIMARY KEY,
  value TINYINT UNSIGNED,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE groups (
  id INTEGER PRIMARY KEY,
  name VARCHAR(80),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE subjects (
  id INTEGER PRIMARY KEY,
  name VARCHAR(80),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
