DROP TABLE IF EXISTS departments;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS lessons;
DROP TABLE IF EXISTS grades;
DROP TABLE IF EXISTS subjects;
DROP TABLE IF EXISTS teachers;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS genders;
DROP TABLE IF EXISTS groups_students;


CREATE TABLE departments (
	department_id INTEGER PRIMARY KEY,
	name VARCHAR(80)
);

CREATE TABLE groups (
  group_id INTEGER PRIMARY KEY,
  name VARCHAR(80),
  department_id INTEGER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT departments_FK FOREIGN KEY (department_id) REFERENCES departments(department_id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE lessons (
  lesson_id INTEGER PRIMARY KEY,
  group_id INTEGER,
  subject_id INTEGER,
  teacher_id INTEGER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT groups_FK FOREIGN KEY (group_id) REFERENCES groups(group_id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT teachers_FK FOREIGN KEY (teacher_id) REFERENCES teachers(teacher_id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT subjects_FK FOREIGN KEY (subject_id) REFERENCES subjects(subject_id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE grades (
  grade_id INTEGER PRIMARY KEY,
  value TINYINT UNSIGNED,
  lesson_id INTEGER,
  CONSTRAINT lessons_FK FOREIGN KEY (lesson_id) REFERENCES lessons(lesson_id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE subjects (
  subject_id INTEGER PRIMARY KEY,
  name VARCHAR(80)
);

CREATE TABLE teachers (
  teacher_id INTEGER PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(40) NOT NULL UNIQUE,
  phone VARCHAR(20) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE students (
	student_id INTEGER PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	email VARCHAR(40) NOT NULL,
	phone VARCHAR(20) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE genders (
  gender_id INTEGER PRIMARY KEY,
  name VARCHAR(30),
  student_id INTEGER,
  teacher_id INTEGER,
  CONSTRAINT students_FK FOREIGN KEY (student_id) REFERENCES students(student_id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT teachers_FK FOREIGN KEY (teacher_id) REFERENCES teachers(teacher_id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE groups_students(
  gs_id INTEGER PRIMARY KEY,
  group_id INTEGER,
  student_id INTEGER,
  CONSTRAINT groups_FK FOREIGN KEY (group_id) REFERENCES groups(group_id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT students_FK FOREIGN KEY (student_id) REFERENCES students(student_id) ON DELETE SET NULL ON UPDATE CASCADE
);
